name: Tweet Old Posts

on:
  schedule:
    - cron: "00 15 * * *"
  workflow_dispatch: 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Tweet Old Posts
        uses: actions/checkout@v2
        with:
          repository: daveabrock/TweetOldPosts  

      - name: Install .NET 
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0' 

      - name: Run app
        env: 
          AccessToken: ${{ secrets.twitter_access_token }}
          AccessSecret: ${{ secrets.twitter_access_token_secret }}
          ConsumerKey: ${{ secrets.twitter_consumer_key }}
          ConsumerSecret: ${{ secrets.twitter_consumer_secret }}
          ConnectionString: ${{ secrets.connection_string }}
        run: dotnet run --project TweetOldPosts -c Release
